import { Inter } from 'next/font/google'
import './globals.css'
// import '../../styles/globals.scss'
// import 'styles/globals.scss'
import '@/styles/globals.scss'
import Provider from './provider'
// import Nav from '@/components/nav'
import Nav from '@/components/nav'


const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Provider>
          <>
          <Nav/>
          <div className='container mx-auto'>
            {children}
          </div>
          </>
        </Provider>  
      </body>
    </html>
  )
}
